# Generated by Django 4.2.2 on 2023-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_order_driver_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture1',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture2',
            field=models.CharField(default='', max_length=500),
        ),
    ]
