# Generated by Django 4.2.2 on 2023-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_item_picture1_alter_item_picture2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='favorite_stores',
            field=models.ManyToManyField(related_name='favorited_by', to='playground.store'),
        ),
    ]
