# Generated by Django 4.2.2 on 2023-06-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_item_picture1_alter_item_picture2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Area',
            new_name='area',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='Zone',
            new_name='zone',
        ),
        migrations.AddField(
            model_name='customer',
            name='favorite_stores',
            field=models.ManyToManyField(related_name='favorited_by', to='playground.store'),
        ),
        migrations.AddField(
            model_name='driver',
            name='area',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='zone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
