# Generated by Django 4.2.2 on 2023-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_customer_favorite_stores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='favorite_stores',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='playground.store'),
        ),
    ]
