# Generated by Django 4.2.2 on 2023-06-22 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_store_picpath_alter_customer_favorite_stores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='playground.customer')),
                ('items', models.ManyToManyField(to='playground.item')),
            ],
        ),
    ]
