# Generated by Django 4.2.2 on 2023-06-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0006_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='items',
            new_name='itemsincart',
        ),
    ]
