# Generated by Django 4.2.2 on 2023-06-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0008_order_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
