# Generated by Django 4.2.2 on 2023-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0009_driver_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('driver_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='playground.driver')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.order')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.store')),
            ],
        ),
    ]
