# Generated by Django 4.2.2 on 2023-06-23 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0012_order_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
