# Generated by Django 4.2.2 on 2023-06-23 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0013_rename_customer_cart_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
