# Generated by Django 4.2.2 on 2023-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0015_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='zone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
