# Generated by Django 4.2.2 on 2023-06-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0016_task_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fromAddress',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='toAddress',
            field=models.CharField(default='', max_length=100),
        ),
    ]
