# Generated by Django 4.2.2 on 2023-06-24 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0017_task_fromaddress_task_toaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='driver_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='playground.driver'),
        ),
    ]
